### ISSUE TITLE
v4 compatibility

### ISSUE THREAD

**Issue by elgohr** [pierre-24/pytimefliplib#2]
Hi, just wanted to ask whether this library is also v4 compatible?
When I try to discover the library doesn't show my v4 timeflip.
Is it my bluetooth (linux) or is the library not compatible?

**Comment by pierre-24** [comment]
The library is not compatible. It would not be difficult to adapt, though, but I prefer having a physical device to perform the test ^^

**Comment by victorhooi** [comment]
How do you know if you have a v4 Timeflip? (I thought the current hardware was Timeflip V2?)

Is there some way to tell the hardware revision?

**Comment by elgohr** [comment]
I found it out by poking against the API

**Comment by pierre-24** [comment]
Thanks to #6, this should now be compatible, so let me know :)
