### ISSUE TITLE
Login not working on TimeFlip v2

### ISSUE THREAD

**Issue by lserni** [pierre-24/pytimefliplib#3]
The Timeflip device (freshly reset by keeping it battery-less overnight) is discovered regularly:

```
Looking around (this can take up to 1 minute) ... Done!
Results::
- TimeFlip devices: C0:BD:96:D4:39:B5 (TimeFlip v2.0)
...

```

However, any attempt to communicate fails:

```
! Connected to C0:BD:96:D4:39:B5
communication error: Not logged in (incorrect password?)
```

Given the protocol, there's precious little diagnostics I can run. Could it be, I don't know, the Bluetooth transmitter?

**Comment by pierre-24** [comment]
Hey :)

Is there a document that describe the protocol of the v2?
