### ISSUE TITLE
License and Contribution guidelines

### ISSUE THREAD

**Issue by unabashed-turbulence** [pierre-24/pytimefliplib#5]
Hello,

I would like to contribute to this repository, however, to do so I need to know what license this source code is being distributed under and what the guidelines for contribution are. If you have the time, could you add documents pertaining to these things to the repository, or tell me in this issue what your policies are?

Thanks,
John C.

**Comment by pierre-24** [comment]
Hello,

You can assume that it is all under MIT. So feel free to contribute if any :)

**Comment by pierre-24** [comment]
That's fixed thanks to  @john-craig :)
